-- MySQL Script generated by MySQL Workbench
-- Tue 10 Jan 2017 17:58:45 AEDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `userPassword` VARCHAR(45) NOT NULL,
  `userEmail` VARCHAR(45) NOT NULL,
  `userLocked` VARCHAR(45) NULL,
  `userUnlockCode` VARCHAR(45) NULL,
  `userType` VARCHAR(45) NOT NULL DEFAULT 'Normal',
  `userLoginAttempt` INT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB
COMMENT = 'Database containing user data';


-- -----------------------------------------------------
-- Table `mydb`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`project` ;

CREATE TABLE IF NOT EXISTS `mydb`.`project` (
  `projectId` INT NOT NULL AUTO_INCREMENT,
  `projectName` VARCHAR(45) NOT NULL,
  `projectProperties` VARCHAR(45) NOT NULL,
  `projectUsers` INT NOT NULL DEFAULT 1,
  `projectPassword` VARCHAR(45) NOT NULL DEFAULT 'password',
  PRIMARY KEY (`projectId`))
ENGINE = InnoDB
COMMENT = 'Contains descriptive data for projects';


-- -----------------------------------------------------
-- Table `mydb`.`userProject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`userProject` ;

CREATE TABLE IF NOT EXISTS `mydb`.`userProject` (
  `userProjectId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `projectId` INT NOT NULL,
  PRIMARY KEY (`userProjectId`))
ENGINE = InnoDB
COMMENT = 'Composite entity for indexing which users are a part of which projects ~ many users can be a part of many projects';


-- -----------------------------------------------------
-- Table `mydb`.`input`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`input` ;

CREATE TABLE IF NOT EXISTS `mydb`.`input` (
  `inputId` INT NOT NULL AUTO_INCREMENT,
  `inputName` VARCHAR(45) NOT NULL,
  `fileUrl` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`inputId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projectInput`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`projectInput` ;

CREATE TABLE IF NOT EXISTS `mydb`.`projectInput` (
  `projectInputId` INT NOT NULL AUTO_INCREMENT,
  `projectId` INT NOT NULL,
  `inputId` INT NOT NULL,
  PRIMARY KEY (`projectInputId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`output`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`output` ;

CREATE TABLE IF NOT EXISTS `mydb`.`output` (
  `outputId` INT NOT NULL AUTO_INCREMENT,
  `outputAlgorithm` VARCHAR(45) NOT NULL,
  `dateMade` VARCHAR(100) NOT NULL,
  `outputFileName` VARCHAR(100) NOT NULL,
  `outputFileUrl` VARCHAR(100) NULL,
  PRIMARY KEY (`outputId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projectOutput`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`projectOutput` ;

CREATE TABLE IF NOT EXISTS `mydb`.`projectOutput` (
  `projectOutputId` INT NOT NULL AUTO_INCREMENT,
  `projectId` INT NOT NULL,
  `outputId` INT NOT NULL,
  PRIMARY KEY (`projectOutputId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aprioriEntries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`aprioriEntries` ;

CREATE TABLE IF NOT EXISTS `mydb`.`aprioriEntries` (
  `aprioriEntriesId` INT NOT NULL AUTO_INCREMENT,
  `outputId` INT NOT NULL,
  `value` VARCHAR(100) NOT NULL,
  `numOfItems` INT NOT NULL,
  `support` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`aprioriEntriesId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inputHasOutput`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`inputHasOutput` ;

CREATE TABLE IF NOT EXISTS `mydb`.`inputHasOutput` (
  `inputHasOutputId` INT UNSIGNED NOT NULL,
  `outputId` INT NOT NULL,
  `inputId` INT NOT NULL,
  PRIMARY KEY (`inputHasOutputId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
